language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout -c ci/travis.cfg
script:
    - ./bin/test
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#django-blog-zinnia"
