sudo: false
dist: xenial
language: python
python:
    - 3.7
    - 3.8
services:
    - postgresql
    - mysql
env:
    - DJANGO=2.2 DATABASE_ENGINE=sqlite
    - DJANGO=2.2 DATABASE_ENGINE=postgres
    - DJANGO=2.2 DATABASE_ENGINE=mysql
    - DJANGO=3.0 DATABASE_ENGINE=sqlite
    - DJANGO=3.0 DATABASE_ENGINE=postgres
    - DJANGO=3.0 DATABASE_ENGINE=mysql
matrix:
    fast_finish: true
install:
    - pip install zc.buildout
    - buildout -c travis.cfg versions:django=$DJANGO testenv:DJANGO_SETTINGS_MODULE=zinnia.tests.implementations.$DATABASE_ENGINE
    - sh -c "if [ '$DATABASE_ENGINE' = 'postgres' ];
      then
        pip install psycopg2;
      fi"
    - sh -c "if [ '$DATABASE_ENGINE' = 'mysql' ];
      then
        pip install mysqlclient;
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql;
      fi"
before_script:
    - ./bin/flake8 zinnia
script:
    - ./bin/test
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#django-blog-zinnia"
