language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
env:
    - DATABASE_ENGINE=sqlite
    - DATABASE_ENGINE=postgres
    - DATABASE_ENGINE=mysql
matrix:
    exclude:
        - python: 3.2
          env: DATABASE_ENGINE=mysql
        - python: 3.3
          env: DATABASE_ENGINE=mysql
    fast_finish: true
install:
    - pip install -U setuptools psycopg2 mysql-python
    - python bootstrap.py
    - ./bin/buildout -c travis.cfg testenv:DJANGO_SETTINGS_MODULE=zinnia.tests.implementations.$DATABASE_ENGINE
    - psql -c 'create database zinnia;' -U postgres;
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql;
    - mysql -e 'create database zinnia CHARACTER SET utf8 COLLATE utf8_general_ci;';
before_script:
    - ./bin/flake8 --exclude=migrations zinnia
script:
    - ./bin/test
after_success:
    - ./bin/coveralls
notifications:
    irc:
        - "irc.freenode.org#django-blog-zinnia"
